### ISSUE TITLE
Two-way binding contentOffset?

### ISSUE THREAD

**Issue by Pash237** [phuhuynh2411/TrackableScrollView#1]
Do you have any ideas for two-way binding?
I mean, getting contentOffset and setting contentOffset of the same ScrollView.

**Comment by phuhuynh2411** [comment]
The ScrollView does not support to do that. You might need to build your own custom ScrollView. I am working this project. When it is ready, I will upload it to github.

Here are the functions that will be added.
- Scroll to top
- Scroll to bottom
- Scroll to Y: scroll to a position in the scroll view.

![custom scrollview](https://user-images.githubusercontent.com/55566346/79032228-ff9a4080-7bce-11ea-9ec3-81ec99604db2.gif)

**Comment by phuhuynh2411** [comment]
If you're interested, check out this repository.
https://github.com/phuhuynh2411/CustomScrollView.git

**Comment by Pash237** [comment]
Oh, this is great!
I tried to go this way myself (reimplementing ScrollView from scratch) but eventually give up and rewrite the whole piece in UIKit :)
